<?php

function isiscb_proxy_menu() {

    $items['isiscb_proxy/json'] = array(
				       'access callback'   => true, // available to all
				       'page callback'     => 'isiscb_proxy_object', // defined below
				       );



    $items['admin/settings/isiscb_proxy'] = array(
						'title' => 'Isis CB Proxy Settings',
						'description' => 'Configure your ISISCB Proxy',
						'page callback' => 'drupal_get_form',
						'page arguments' => array('isiscb_proxy_admin'),
						'access arguments' => array('administer isiscb_proxy settings'),
						'type' => MENU_NORMAL_ITEM,
						);
			   



    return $items;
}



function isiscb_proxy_admin() {


}




function isiscb_proxy_object() {
    $url="http://data.isiscb.org/rest/?format=json";

    /* check for cached data based on url */


    /* if cache miss, get from IsisCB */
    $response = drupal_http_request($url);
    $data = json_decode($response->data);



    return $data;
}