<?php

function isiscb_proxy_menu() {
    $items['isiscb_proxy_json']
	= array(
		'access callback'   => true, 
		'page callback'     => 'isiscb_proxy_object', 
		'delivery callback' => drupal_json_output
		);
    /* add title to admin form */
    $items['admin/config/isiscb']
	= array(
		'title' => 'Isis CB',
		'description' => 'Isis CB releated settings',
		'position' => 'right', 
		'weight' => -15,
		'page callback' => 'system_admin_menu_block_page', 
		'access arguments' => array('administer site configuration'), 
		'file' => 'system.admin.inc', 
		'file path' => drupal_get_path('module', 'system'), 
		);
    
    /* proxy settings */
    $items['admin/config/isiscb/proxy']
	= array(
		'title' => 'Isis CB Proxy Settings',
		'description' => 'Configure your Isis CB Proxy',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('isiscb_proxy_settings'),
		'access arguments' => array('administer isiscb_proxy settings'),
		'weight' => -10,
		);

    return $items;
}



function isiscb_proxy_settings() {

    $form = array();

    $form['isiscb_proxy_id']
	= array(
		'#type' => 'textfield',
		'#title' => t('Isis CB Client ID'),
		'#default_value' => variable_get('onthisdate_maxdisp', ""),
		'#description' => t("Client ID to use for retrieving data"),
		'#required' => TRUE,
		);

    $form['isiscb_proxy_pass']
	= array(
		'#type' => 'password',
		'#title' => t('Isis CB Client Password'),
		'#default_value' => variable_get('onthisdate_maxdisp', ""),
		'#description' => t("Client password to use for retrieving data"),
		'#required' => TRUE,
		);

    return system_settings_form($form);
    
}




function isiscb_proxy_object() {

    /* get query to proxy from url */
    $mypath = substr(request_path(), strlen('isiscb_proxy_json'));

    /* Drupal cache system magic to cache the json response, keyed on
       the query path */
    $isisdata = &drupal_static(__FUNCTION__); 
    if (!isset( $isisdata[$mypath] )) {
    
	if ($cache = cache_get("isiscb".$mypath)) {
	    $isisdata[$mypath] = $cache->data;
	}
	else {
	    /* CACHE MISS! need to  actually get JSON from ISIS CB */
	    /* this part needs to be smarter */
	    $isis_url="http://data.isiscb.org/rest/${mypath}?format=json";	    
	    $response = drupal_http_request($isis_url);
	    $isisdata[$mypath] = json_decode($response->data);

	    $isisdata[$mypath]->{'proxied'}=time();	       

	    cache_set("isiscb".$mypath, $isisdata[$mypath], 'cache');
	}
    }
    
    return $isisdata[$mypath];
}